"use strict";

require('dotenv').config();
var rp = require('request-promise');

var baseURL = 'https://api.lightrail.com/v1/';
var customHeaders = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer ' + process.env.ACCESS_TOKEN
};

// CREATING A CONTACT

// Parameter 'contact' is expected to be an object
// with mandatory property 'id'
// and optional properties 'email', 'firstName', 'lastName'
function createContact(contact) {
  // TODO: validate argument
  rp({
    method: 'POST',
    uri: baseURL + 'contacts',
    headers: customHeaders,
    body: {
      'userSuppliedId': contact.id,
      'email': contact.email,
      'firstName': contact.firstName,
      'lastName': contact.lastName
    },
    json: true
  })
  .then(function(returnedContact) {
    // TODO: save returned contact object instead of logging it
    //       & save ID generated by Lightrail
    console.log(returnedContact);
  })
  .catch(function(err) {
    // TODO: better error handling
    console.log(err);
  });
}



// // FUNCTIONALITY CHECKING
//
// // Contact creation
//
// var sampleContact = {
//   'id': '10101010101010',
//   'email': 'ex@example.com'
// }
// createContact(sampleContact);
