"use strict";

require('dotenv').config();
var rp = require('request-promise');

var baseURL = 'https://api.lightrail.com/v1/';
var customHeaders = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer ' + process.env.ACCESS_TOKEN
};

// CREATING A CONTACT

// Parameter 'contact' is expected to be an object
// with mandatory property 'id'
// and optional properties 'email', 'firstName', 'lastName'
function createContact(contact) {
  // TODO: validate argument
  rp({
    method: 'POST',
    uri: baseURL + 'contacts',
    headers: customHeaders,
    body: {
      'userSuppliedId': contact.id,
      'email': contact.email,
      'firstName': contact.firstName,
      'lastName': contact.lastName
    },
    json: true
  })
  .then(function(returnedContact) {
    // TODO: save returned contact object instead of logging it
    //       & save ID generated by Lightrail
    console.log(returnedContact);
  })
  .catch(function(err) {
    // TODO: better error handling
    console.log(err);
  });
}

// CREATING A CARD

// Parameter 'card' is expected to be an object
// with mandatory properties 'id', 'value', and 'programId'
// and optional properties 'categories' and 'contactId'
function createPointsCard(card) {
  // TODO: validate argument
  rp({
    method: 'POST',
    uri: baseURL + 'cards',
    headers: customHeaders,
    body: {
      'userSuppliedId': card.id,
      'code': {
        'initialValue': card.value,
        // Since this is a points card, hardcode to non-currency
        'currency': 'XXX',
        'programId': card.programId
      },
      // TODO: handle undefined for optional fields (eg default to {} or '')
      'categories': card.categories,
      'contactId': card.contactId
    },
    json: true
  })
  .then(function(returnedCard) {
    // TODO: save returned card instead of logging it
    //       & update local card obj with Lightrail ID
    console.log(returnedCard);
  })
  .catch(function(err) {
    // TODO: better error handling
    console.log(err);
  });
}



// // FUNCTIONALITY CHECKING
//
// // Contact creation
//
// var sampleContact = {
//   'id': '10101010101010',
//   'email': 'ex@example.com'
// }
// createContact(sampleContact);
//
// // Card creation
//
// var card = {
//   'id': '1010101010101010',
//   'lightrailId': 'card-99812714217a460d88383852bdfe0204',
//   'value': '5',
//   'programId': 'program-eb6f3e8b9d7548a0b51b872375f635c3',
//   'categories': {},
//   'contactId': 'contact-f1a7888f803d4e2d815e3d9447fbf276'
// };
// createPointsCard(card);
